### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by architecb33** [apppresser/ap3#1]
i have follow the steps, but when i run ionic serve, i got typescript error..

![screen shot 2016-12-08 at 1 48 52 am](https://cloud.githubusercontent.com/assets/3340840/20981823/ac639964-bce8-11e6-9c78-b2111559da3f.jpg)
![screen shot 2016-12-08 at 1 48 59 am](https://cloud.githubusercontent.com/assets/3340840/20981826/acd4128e-bce8-11e6-8590-8d65ea71b3bc.jpg)

**Comment by scottopolis** [comment]
Try

ionic plugin add cordova-plugin-device

http://ionicframework.com/docs/v2/native/device/

**Comment by architecb33** [comment]
still no luck :(

**Comment by stillatmylinux** [comment]
@architecb33 This code has been updated to just Device.platform.  That should take care of your issue.
