### ISSUE TITLE
Crash in app.component.ts:resetSideMenu() when item.extra_classes is undefined

### ISSUE THREAD

**Issue by chrisperkins** [apppresser/ap3#2]
Adding a custom page component per the remarks in app.component.ts:loadMenu() causes a crash in app.component.ts:resetSideMenu() when item.extra_classes is undefined. Adding 'extra_classes': "" to the page object restores normal functionality. 

Revising the comments referencing the addition of custom menu items would be helpful if the extra_classes key is required.

**Comment by scottopolis** [comment]
Hi Chris, ya that comment needs updating. Thanks for the report.

**Comment by stillatmylinux** [comment]
@chrisperkins We got that updated.  thanks
